healthstack_patient:
    resource: "@HealthstackBundle/Resources/config/routing/patient.yml"
    prefix:   /patient

healthstack_medicine:
    resource: "@HealthstackBundle/Resources/config/routing/medicine.yml"
    prefix:   /medicine

healthstack_ticket:
    resource: "@HealthstackBundle/Resources/config/routing/ticket.yml"
    prefix:   /ticket

healthstack_homepage:
    path:     /
    defaults: { _controller: HealthstackBundle:Default:index }

api_auth:
    path:     /api/auth
    defaults: { _controller: "HealthstackBundle:Api:auth" }
    methods:  POST

api_tickets:
    path:     /api/tickets
    defaults: { _controller: "HealthstackBundle:Api:tickets" }
    methods:  POST
